stages:
  - development
  - staging
  - production

variables:
  GIT_SUBMODULE_STRATEGY: recursive

update-submodule:
  stage: development
  tags:
    - shell-build-test
  only:
    - master
  when: manual
  interruptible: false
  script:
     - eval $(ssh-agent -s)
     - chmod 700 "$GIT_SSH_PRIV_KEY"
     - ssh-add "$GIT_SSH_PRIV_KEY"
     - git config user.email "git@leo9000.de"
     - git config user.name "Leo9000 (Gitlab)"
     - git remote set-url origin git@git.leo9000.de:mpg-hirnforschung/ns-medical-victims-docker.git
     - cd zefiro
        && git fetch --all
        && git checkout origin/master
        && CMS_COMMIT=$(git rev-parse --short HEAD)
        && cd ..
        && git commit -m "Update CMS to ${CMS_COMMIT}"
        && git push -u origin master
     # TODO: Add success check
  environment:
    name: build-test

# run nmv, build or re-create the container if required
deploy-staging:
  retry: 2
  stage: staging
  tags:
    - shell-staging
  only:
    - master
  interruptible: false
  script:
     # configure the PHP application
     # we might replace this later on by a script or read
     # the values from env in PHP config file
     - ln -fn /opt/config/ns-medical-victims-config-staging.php ./zefiro/custom/config.php
     - docker info
     - docker images
     - docker-compose -p ns-medical-victims-staging up -d zefiro db phpmyadmin
     # TODO: Add success check
  environment:
    name: staging
    url: https://staging.ns-medical-victims.org

# load database from dump
load database:
  stage: staging
  tags:
    - shell-staging
  only:
    - master
  when: manual
  interruptible: false
  script:
     - docker-compose -p ns-medical-victims-staging up -d db
     - DIR="/opt/backups/ns-medical-victims-docker/"
       && xz --stdout --force --keep --verbose --decompress
         "${DIR}latest.sql.xz"
         | docker exec -i "$(docker-compose -p ns-medical-victims-staging ps -q db)" sh -c 
                  'mysql -uroot -p"$MYSQL_ROOT_PASSWORD"'
     - docker-compose exec -T db sh -c 'mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -e
            "FLUSH PRIVILEGES;"'
  environment:
    name: staging
    url: https://staging.ns-medical-victims.org

# run nmv, build or re-create the container if required
run:
  retry: 2
  stage: production
  tags:
    - shell-production
  only:
    - master
  when: manual
  interruptible: false
  script:
     # configure the PHP application
     # we might replace this later on by a script or read
     # the values from env in PHP config file
     - ln -fn /opt/config/ns-medical-victims-config.php ./zefiro/custom/config.php
     - docker info
     - docker images
     - docker-compose up -d zefiro db phpmyadmin
     # TODO: Add success check
  environment:
    name: production
    url: https://ns-medical-victims.org

# load the latest image from the docker registry,
# build and if neccessary re-create the container
upgrade:
  retry: 2
  stage: production
  tags:
    - shell-production
  only:
    - master
  when: manual
  interruptible: false
  script:
     # configure the PHP application
     # we might replace this later on by a script or read
     # the values from env in PHP config file
     - ln -fn /opt/config/ns-medical-victims-config.php ./zefiro/custom/config.php
     - docker info
     - docker images
     - docker-compose pull db phpmyadmin
     - docker-compose build --pull --no-cache zefiro
     - docker-compose up -d zefiro db phpmyadmin
     # TODO: Add success check
  environment:
    name: production
    url: https://ns-medical-victims.org

# stop and tear down containers
down:
  retry: 2
  stage: production
  tags:
    - shell-production
  only:
    - master
  when: manual
  interruptible: false
  script:
    - docker-compose down
  environment:
    name: production
    url: https://ns-medical-victims.org

# restart containers
restart:
  retry: 2
  stage: production
  tags:
    - shell-production
  only:
    - master
  when: manual
  interruptible: false
  script:
     - docker-compose restart
  environment:
    name: production
    url: https://ns-medical-victims.org

# create database dump
backup database:
  stage: production
  tags:
    - shell-production
  only:
    - master
  when: manual
  interruptible: false
  script:
     - docker-compose up -d db
     - NOW="$(date --utc +'%Y-%m-%d_%H:%M:%S_UTC')"
       && DIR="/opt/backups/ns-medical-victims-docker/"
       && docker-compose exec -T db sh -c
          'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"'
          | xz --stdout > "${DIR}${NOW}.sql.xz"
       && ln -sfr "${DIR}${NOW}.sql.xz" "${DIR}latest.sql.xz"
     - ls -lh /opt/backups/ns-medical-victims-docker/
  environment:
    name: production
    url: https://ns-medical-victims.org

# create database dump
delete old backups:
  stage: production
  tags:
    - shell-production
  only:
    - master
  when: manual
  interruptible: false
  script:
     - ls -lh /opt/backups/ns-medical-victims-docker/
     - find /opt/backups/ns-medical-victims-docker/* -mtime +31 -exec rm {} \;
     - ls -lh /opt/backups/ns-medical-victims-docker/
  environment:
    name: production
    url: https://ns-medical-victims.org

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

