version: '3.5'

services:
  zefiro:
    image: zefiro-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: '${NMV_HOSTNAME:-ns-medical-victims.org}'
      LETSENCRYPT_HOST: '${NMV_HOSTNAME:-ns-medical-victims.org}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
    volumes:
      - "./zefiro:/var/www/html"
    networks:
      - default
      - proxy-network

  zefiro-dev:
    image: zefiro-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "./zefiro:/var/www/html"
    ports:
      - "${NMV_DEV_PORT}:80"

  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - mariadbdata:/var/lib/mysql
      - mariadblog:/var/log/mysql

#  adminer:
#    image: adminer
#    restart: always
#    environment:
#      VIRTUAL_HOST: '${NMV_ADMINER_HOSTNAME:-adminer.ns-medical-victims.org}'
#      LETSENCRYPT_HOST: '${NMV_ADMINER_HOSTNAME:-adminer.ns-medical-victims.org}'
#      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
#    networks:
#      - default
#      - proxy-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      VIRTUAL_HOST: '${NMV_PMA_HOSTNAME:-mysql.ns-medical-victims.org}'
      LETSENCRYPT_HOST: '${NMV_PMA_HOSTNAME:-mysql.ns-medical-victims.org}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: 'https://${NMV_PMA_HOSTNAME:-mysql.ns-medical-victims.org}'
    networks:
      - default
      - proxy-network

#  files:
#    image: afian/filerun
#    restart: always
#    environment:
#      VIRTUAL_HOST: '${NMV_FILERUN_HOSTNAME:-files.ns-medical-victims.org}'
#      LETSENCRYPT_HOST: ${NMV_FILERUN_HOSTNAME:-files.ns-medical-victims.org}'
#      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
#      FR_DB_HOST: db
#      FR_DB_PORT: 3306
#      FR_DB_NAME: '${NMV_FILERUN_DB_NAME}'
#      FR_DB_USER: '${NMV_FILERUN_DB_USER}'
#      FR_DB_PASS: '${NMV_FILERUN_DB_PASS}'
#    volumes:
#      - ./zefiro:/user-files
#    networks:
#      - default
#      - proxy-network

#  sftp:
#    image: atmoz/sftp:alpine
#    restart: always
#    volumes:
#      - './zefiro:/home/${SFTP_USER}/zefiro'
#      - 'sftpconfig:/etc/sftp:ro'
#    ports:
#      - "3927:22"

volumes:
  mariadbdata:
  mariadblog:
#  sftpconfig:

networks:
  proxy-network:
    name: global-proxy-network

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

